export enum SortBy {
  NAME = 'name',
  DEPARTMENT = 'department',
  REQUESTER = 'requester',
  STATUS = 'status',
  GOAL = 'goal',
  IMPACT_STAKEHOLDERS = 'impactStakeholders',
  COMPLEXITY = 'complexity',
  MONTHLY_REQUESTS = 'monthlyRequests',
  AVERAGE_TIME_SPENT = 'averageTimeSpent',
  MONTHLY_MINUTES_SAVED = 'monthlyMinutesSaved',
  FINANCIAL_GAIN = 'financialGain',
  RANGE_OF_GAIN = 'rangeOfGain',
  PRIORITY_LEVEL = 'priorityLevel',
  REQUEST_DATE = 'requestDate',
}
